// Session
const SET_TOKEN = "SET_TOKEN";

// User
const SET_USER = "SET_USER";
const CLEAR_USER = "CLEAR_USER";
const LOADING_USER = "LOADING_USER";
const CLEAR_IS_USER_LOADING = "CLEAR_IS_USER_LOADING";
const CLEAR_LOADING_USER = "CLEAR_LOADING_USER";

// ERRORS
const SET_ERRORS = "SET_ERRORS";
const CLEAR_ERRORS = "CLEAR_ERRORS";

// TODOS
const SET_TODOS = "SET_TODOS";
const LOADING_TODOS = "LOADING_TODOS";
const CREATE_TODO = "CREATE_TODOS";
const LOADING_SINGLE_TODO = "LOADING_SINGLE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";
const CLEAR_LOADING_SINGLE_TODO = "CLEAR_LOADING_SINGLE_TODO";

export {
  // Session
  SET_TOKEN,
  // User
  SET_USER,
  CLEAR_USER,
  LOADING_USER,
  CLEAR_IS_USER_LOADING,
  CLEAR_LOADING_USER,
  // ERRORS
  SET_ERRORS,
  CLEAR_ERRORS,
  // TODOS
  SET_TODOS,
  LOADING_TODOS,
  CREATE_TODO,
  LOADING_SINGLE_TODO,
  UPDATE_TODO,
  DELETE_TODO,
  CLEAR_LOADING_SINGLE_TODO,
};
